services:
  postgres:
    container_name: postgres-desafio-ruk
    image: bitnami/postgresql:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
    - postgres_data:/bitnami/postgressql/
volumes:
  postgres_data:   

